// Traditional lookup matrix from bdp-raymon/chinese-gender-prediction (MIT).
// Source revision: 8c5338d043a85ad3b4de2af0dd516bd6c7d2b62b.
// See THIRD-PARTY-NOTICES.md. Different circulating versions may disagree.
const rows = ['GBGBBBBBBBBB','BGBGGBBBBBGG','GBGBBBBBBGBB','BGGGGGGGGGGG','GBBGBGGBGGGG','BBGBBGBGBBBG','BGBBGBBGGGGG','GBBGGBGBBBBB','BGBGGBGBGGGG','GBGBGGBBBBGB','BGBGGGBBBBGG','GBGGBBBBBGGG','BGGGGGGGGGBB','BGBGGGGGGGGB','BGBGGGGGGGGB','GBGBGGGBGGGB','BGBGGGGGGGBB','BBGBGGGBGGBB','GBBGBGGGBBBB','BGBBGBGBGBGB','GBGBBGBGBGBG','BGBBBGGBGBGG','GBGBGBBGBGBG','BGBGBGBBGBGB','GBGBGBGBBGBG','BGBGBGBGBBBB','BBGBBBGBGBGG','GBBGGGBGBGBB'];
export const CHART = Object.fromEntries(rows.map((row,i)=>[i+18,row]));
export const CHART_VERSION = 'traditional-bdp-raymon-v1';
