import {icon} from './templates.mjs';

function downloads(slug,label){
  return `<div class="download-actions"><a class="button secondary small" href="/downloads/gender-reveal-${slug}-a4.pdf" download>${icon('download-simple')}${label}: A4 PDF</a><a class="button secondary small" href="/downloads/gender-reveal-${slug}-letter.pdf" download>${icon('download-simple')}${label}: US Letter PDF</a></div>`;
}

function preview(slug,alt,caption){
  return `<figure class="game-preview"><img src="/assets/games-${slug}-preview.png" alt="${alt}" width="540" height="764" loading="lazy"><figcaption>${caption}</figcaption></figure>`;
}

export function gamesBody(){return `
<div class="note-box"><p><strong>Make a guess, share a message, or play a word game.</strong> These activities work before or after an announcement. The parents choose what to share; a guest vote or traditional chart is not a way to establish a baby’s sex.</p></div>
<div class="download-box" id="download"><h2>Download the free printable gender reveal games</h2><p>The nine-page party kit includes prediction cards, a team vote sheet, an A-Z name race, eight different Bingo cards, and a word scramble with a separate answer page. Choose A4 or US Letter. No email or account is needed.</p><div class="download-actions"><a class="button primary small" href="/downloads/gender-reveal-games-a4.pdf" download>${icon('download-simple')}Complete kit: A4 PDF</a><a class="button secondary small" href="/downloads/gender-reveal-games-letter.pdf" download>${icon('download-simple')}Complete kit: US Letter PDF</a></div><p class="small-copy">Single-game downloads are beside each set of instructions below. Keep the word-scramble answers with the host.</p></div>
<nav class="resource-links" aria-label="Choose a party game"><a href="#prediction-cards">Prediction cards</a><a href="#team-vote">Team vote</a><a href="#name-race">Name race</a><a href="#bingo">Bingo</a><a href="#word-scramble">Word scramble</a></nav>
<h2>Choose a game for your gathering</h2>
<div class="table-wrap" tabindex="0" role="region" aria-label="Printable game comparison"><table class="month-table"><caption>Five games at a glance</caption><thead><tr><th scope="col">Game</th><th scope="col">Players</th><th scope="col">When to use it</th><th scope="col">Complete-kit pages</th></tr></thead><tbody><tr><th scope="row">Prediction cards</th><td>Any number</td><td>Arrival or a quiet moment</td><td>1</td></tr><tr><th scope="row">Team vote</th><td>Any number</td><td>Before the announcement</td><td>2</td></tr><tr><th scope="row">A-Z name race</th><td>2+, alone or in pairs</td><td>A three-minute round</td><td>3</td></tr><tr><th scope="row">Party-moment Bingo</th><td>2-8 with unique cards</td><td>Throughout the gathering</td><td>4-7</td></tr><tr><th scope="row">Word scramble</th><td>2+, alone or in pairs</td><td>A short round; answers for the host</td><td>8-9</td></tr></tbody></table></div>
<h2 id="prediction-cards">1. Boy or girl prediction cards</h2><p><strong>Players:</strong> any number. <strong>Time:</strong> a few minutes. <strong>Print:</strong> page 1 has four cards; give one to each guest.</p>
${preview('prediction-cards','Four printable guest prediction cards with a boy-or-girl guess and a message for the baby.','A keepsake card guests can fill in without sharing personal pregnancy dates.')}
<ol><li>Put the cards and pens where guests arrive.</li><li>Invite each guest to mark a guess and write a message. Anyone can leave the guess blank.</li><li>Collect the cards before the announcement, then keep the messages as a memento.</li></ol><p>For a small gathering, read the messages together afterward. The guesses are part of the game and do not affect the announcement.</p>${downloads('prediction-cards','Prediction cards')}
<h2 id="team-vote">2. Team vote</h2><p><strong>Players:</strong> any number. <strong>Time:</strong> one minute per guest. <strong>Print:</strong> one copy of page 2 for up to 20 guests; print extra copies for a larger group.</p>
${preview('team-vote','A printable voting sheet with guest-name rows and Boy, Girl and Surprise checkboxes.','One shared sheet makes it easy to count the group’s guesses.')}
<ol><li>Place the sheet and a pen on a table where everyone can reach it.</li><li>Each guest writes their name on one row and marks one choice: Boy, Girl or Surprise.</li><li>Close voting before the announcement and count the checked boxes in each column. Each person gets one vote; a tie is fine.</li></ol><p>Leave participation optional. The result is a guest poll, not evidence about the pregnancy.</p>${downloads('team-vote','Team vote')}
<h2 id="name-race">3. The A-Z baby-name race</h2><p><strong>Players:</strong> two or more, individually or in pairs. <strong>Time:</strong> three minutes, plus time to compare. <strong>Print:</strong> one copy of page 3 per player or pair.</p>
${preview('name-race','An A to Z baby-name race with a writing line for each letter and a total score.','A word game that works before or after the announcement.')}
<ol><li>Agree to use first names, for any gender, starting with A to Z.</li><li>Set a timer for three minutes and write one name beside as many letters as possible.</li><li>Award one point for each completed letter with a name the group recognizes. The maximum score is 26; tied players share the win.</li></ol><p>Pair younger guests with an adult or skip the timer. The parents do not need to choose a name from the answers.</p>${downloads('name-race','Name race')}
<h2 id="bingo">4. Gender reveal Bingo</h2><p><strong>Players:</strong> two to eight with distinct cards; larger groups can play in pairs. <strong>Time:</strong> throughout the gathering. <strong>Print:</strong> pages 4-7 have eight different cards, two on each page.</p>
${preview('bingo','Two different party-moment Bingo cards with a free center square and prompts guests can spot at a gathering.','Eight different arrangements help guests play at their own pace.')}
<ol><li>Cut out the cards and give each player or pair a different numbered card.</li><li>Use pens to mark ordinary party moments as they happen. The center square is free.</li><li>The first player to complete a row, column or diagonal calls Bingo. Check the marked moments together; simultaneous winners share the win.</li></ol><p>Do not ask anyone to perform an uncomfortable prompt just to complete a line. For a quieter gathering, play for the most observed squares by the end. If you reuse a card for a larger group, those guests may tie.</p>${downloads('bingo','Bingo cards')}
<h2 id="word-scramble">5. Baby word scramble</h2><p><strong>Players:</strong> two or more, individually or in pairs. <strong>Time:</strong> three to five minutes. <strong>Print:</strong> page 8 for each player; page 9 is the host’s answer key.</p>
${preview('word-scramble','A printable baby word scramble with ten mixed-up words, answer lines and space for a score.','A short word puzzle with an answer page included in the download.')}
<ol><li>Hand out the puzzle page and keep the answer key out of view.</li><li>Set the time limit, or work together without a timer.</li><li>Give one point for each correct word, for a maximum of ten. Read the answers together and share the win if scores tie.</li></ol><p>Adults and children can form pairs. These words are party vocabulary; solving them does not reveal information about the baby.</p>${downloads('word-scramble','Word scramble and answers')}
<h2>A simple party order</h2><ol><li><strong>At arrival:</strong> offer prediction cards and the team vote.</li><li><strong>During the gathering:</strong> hand out Bingo cards and choose either the name race or word scramble for a short round.</li><li><strong>Before the announcement:</strong> collect cards and close voting.</li><li><strong>Afterward:</strong> share messages and keep the cards.</li></ol><p>You do not need to run every activity. Two games and time to talk can be enough for a small gathering.</p>
<h2>Add one traditional guess</h2><p>If the parents would enjoy it, they can privately use the <a href="/#predictor">Chinese gender predictor</a> and share just the chart’s guess. The <a href="/chinese-gender-calendar-2026/">2026</a> and <a href="/chinese-gender-calendar-2027/">2027 printable calendars</a> explain the lookup. Our <a href="/old-wives-tales-gender-prediction/#download">old wives’ tales game</a> offers a separate, optional folklore record sheet.</p><p><a href="/accuracy/#calendar-accuracy">Research does not support the chart as a reliable prediction.</a> Use an announcement supplied by the parents for any reveal activity.</p>
<h2>Printing and permission</h2><p>These five game layouts were created for Chinese Gender Predictor. You may print them for personal, noncommercial events, including copies for your guests. Please share a link to this page instead of redistributing or selling the files, and keep the source credit on your copies.</p><p>Choose the PDF matching your paper: A4 is 210 × 297 mm; US Letter is 8.5 × 11 inches. Print at actual size or 100% scale. Use single-sided printing for cards you will cut apart and keep answer sheets with the host. <a href="/terms/">Read the terms of use.</a></p>`;}
