import {esc,form,resultPanel,icon,chartTable} from './templates.mjs';
import {calendarMonths} from './calendar.mjs';
const study='https://pubmed.ncbi.nlm.nih.gov/20618730/';
const recentStudy='https://www.actualgyn.com/pdf/en_2023_281.pdf';
const chart='https://github.com/bdp-raymon/chinese-gender-prediction/blob/8c5338d043a85ad3b4de2af0dd516bd6c7d2b62b/src/calendar.php';
const lunar='https://github.com/6tail/lunar-javascript';
const hko='https://www.hko.gov.hk/en/gts/time/conversion.htm';
const dateLabel=value=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));
function editorial(){return `<p class="editorial-meta">Maintained by <a href="/about/">BogerHou</a> · Reviewed October 9, 2026</p>`;}
function aside(){return `<aside class="article-aside"><h2>Keep exploring</h2><a href="/lunar-age-calculator/">Calculate your lunar age</a><a href="/chinese-gender-calendar-2026/">2026 calendar & printable chart</a><a href="/chinese-gender-calendar-2027/">2027 calendar & printable chart</a><a href="/how-it-works/">How the chart works</a><a href="/accuracy/">What the research says</a><a href="/gender-reveal-games/">Free printable party games</a><a class="button primary" href="/">Open predictor</a></aside>`;}
function article(title,description,content){return `<section class="container article-section"><div class="breadcrumb"><a href="/">Home</a> / ${esc(title)}</div><header class="article-header"><h1>${title}</h1><p>${description}</p>${editorial()}</header><div class="article-layout"><article class="prose">${content}</article>${aside()}</div></section>`;}
export function agePage(){return `<section class="container article-section age-tool"><div class="breadcrumb"><a href="/">Home</a> / Lunar age calculator</div><header class="article-header"><h1>Lunar Age Calculator</h1><p>Find your traditional Chinese age on a specific date. No need to convert your birthday yourself.</p>${editorial()}</header><div class="tool-grid">${form({ageOnly:true})}${resultPanel({ageOnly:true})}</div><div class="article-layout"><article class="prose"><h2>How Chinese lunar age is counted</h2><p>This calculator follows a traditional nominal-age convention: you are one year old at birth and gain one year at each Chinese New Year. That makes your lunar age different from your completed years since birth.</p><div class="note-box"><p class="formula">Lunar age = target lunar year − birth lunar year + 1</p></div><p>The important detail is <em>lunar year</em>. A birthday in January or early February may belong to the preceding lunar year. Simply adding one to your regular age can give the wrong answer.</p><h2>A worked example</h2><p>Someone born on June 1, 2000 belongs to lunar year 2000. On February 16, 2026, the lunar year is still 2025, so their lunar age is 2025 − 2000 + 1 = <strong>26</strong>. The next day is Chinese New Year: the lunar year changes to 2026 and their lunar age becomes <strong>27</strong>.</p><h2>Using this age with the gender chart</h2><p>The traditional gender chart uses age at <strong>conception</strong>. Choose that date here if you are looking up the chart manually. The <a href="/">Chinese gender predictor</a> performs this conversion automatically and also finds the lunar conception month.</p><p>The age calculation describes a calendar convention. It does not add scientific validity to the gender chart. <a href="/accuracy/">Read the evidence on prediction accuracy.</a></p><h2>Dates and limits</h2><p>The date converter accepts years 1900 to 2099. The gender chart itself only contains lunar ages 18 to 45; this separate age calculator can display ages outside that range. Very distant future calendar dates can be subject to astronomical calculation differences near midnight.</p><p class="source-list">Calendar conversion: <a href="${lunar}">lunar-javascript</a>. Independent date reference: <a href="${hko}">Hong Kong Observatory conversion tables</a>.</p></article>${aside()}</div></section>`;}
const yearDetails={
  2026:{newYear:'February 17, 2026',previousEnd:'February 16',partial:'Lunar month 11 of 2025 starts in December 2025; lunar month 11 of 2026 continues into January 2027.',boundary:'February 16, 2026 is in lunar year 2025, month 12. February 17 is in lunar year 2026, month 1.',example:'For a mother born June 15, 1995, conception on May 1, 2026 falls in lunar year 2026, month 3. Her lunar age is 32, and row 32, column 3 reads Boy in this chart.'},
  2027:{newYear:'February 6, 2027',previousEnd:'February 5',partial:'Lunar month 11 of 2026 starts in December 2026; lunar month 12 of 2027 continues into January 2028.',boundary:'February 5, 2027 is in lunar year 2026, month 12. February 6 is in lunar year 2027, month 1.',example:'For a mother born June 15, 1995, conception on February 5, 2027 uses lunar age 32 and month 12. Conception on February 6 uses lunar age 33 and month 1. Both coordinates change at Chinese New Year.'}
};
export function yearPage(year=2027){const months=calendarMonths(year),detail=yearDetails[year];return article(`Chinese Gender Calendar ${year}`,`Find the lunar month for a conception date in ${year}, read the complete traditional gender chart, or download a free printable PDF.`,`
<nav class="year-nav" aria-label="Calendar year"><a href="/chinese-gender-calendar-2026/"${year===2026?' aria-current="page"':''}>2026 calendar</a><a href="/chinese-gender-calendar-2027/"${year===2027?' aria-current="page"':''}>2027 calendar</a></nav>
<div class="note-box"><p><strong>Chinese New Year is ${detail.newYear}.</strong> January 1 through ${detail.previousEnd} still belongs to lunar year ${year-1}. The chart uses your age and month at conception, even if the baby is due in another year.</p></div>
<div class="download-box" id="download"><h2>Download the ${year} calendar PDF</h2><p>This two-page PDF keeps the full chart, Gregorian-to-lunar month dates, lookup instructions and source notes together. Choose your paper size and print at actual size or 100% scale.</p><div class="download-actions"><a class="button secondary small" href="/downloads/chinese-gender-calendar-${year}-a4.pdf" download>${icon('download-simple')}Download A4 PDF</a><a class="button secondary small" href="/downloads/chinese-gender-calendar-${year}-letter.pdf" download>${icon('download-simple')}Download US Letter PDF</a></div><p class="small-copy">Free for personal reference. The traditional chart is for entertainment, not a medical prediction.</p></div>
<h2 id="lunar-months">Find the lunar month for your date</h2><p>Use the <strong>estimated conception date</strong>, not the due date. This table shows the part of each lunar month that falls within Gregorian year ${year}. The first and last rows are partial months.</p>
<div class="table-wrap" tabindex="0" role="region" aria-label="${year} Gregorian to lunar month reference"><table class="month-table"><caption>Lunar months within Gregorian year ${year}</caption><thead><tr><th scope="col">Gregorian dates (inclusive)</th><th scope="col">Lunar year</th><th scope="col">Lunar month</th></tr></thead><tbody>${months.map((m,i)=>`<tr><td>${dateLabel(m.start)} to ${dateLabel(m.end)}${i===0||i===months.length-1?' *':''}</td><td>${m.year}</td><td>${m.leap?'Leap ':''}${m.month}</td></tr>`).join('')}</tbody></table></div>
<p class="small-copy">* Only days within ${year} are shown. ${detail.partial} There is no leap lunar month within Gregorian year ${year}.</p>
<h2 id="chinese-gender-chart">The complete ${year} Chinese gender chart</h2><p>The traditional matrix is the same each year. The changing lunar dates above determine which column you use. Find the mother’s <a href="/lunar-age-calculator/">lunar age at conception</a> in rows 18 to 45, then read across to the lunar month. B means Boy and G means Girl.</p>${chartTable()}
<h2>How to use the calendar</h2><ol><li>Find your estimated conception date in the month table above.</li><li>Calculate your lunar age on that date. The count is one at birth, then increases at each Chinese New Year.</li><li>Read the chart cell where that age and lunar month meet.</li></ol><p>${detail.example} This is a lookup example, not evidence about an actual pregnancy. The <a href="/">Chinese gender predictor</a> converts both dates automatically and explains the result.</p>
<h2>Why the New Year boundary matters</h2><p>${detail.boundary} The traditional age count also increases at that boundary. Moving a date by one day can change two chart coordinates. Do not substitute January 1 for Chinese New Year or use a regular age without converting it.</p>
<h2 id="due-date">Due in 2027? You may need the 2026 calendar</h2><p>Choose the calendar for the <strong>estimated conception year</strong>. For example, a due date of January 22, 2027 gives an estimated conception date of May 1, 2026 when we subtract 266 days. That lookup uses lunar month 3 of 2026, not the month of birth in 2027.</p><p>This subtraction is an approximation, not a way to identify the actual conception day. If you only know the due date, the <a href="/">calculator’s Due date option</a> handles the estimate. You can compare the <a href="/chinese-gender-calendar-2026/">2026 month dates</a> and <a href="/chinese-gender-calendar-2027/">2027 month dates</a> here.</p>
<h2>Does a year-specific chart improve accuracy?</h2><p>It helps you look up the right lunar dates. It does not make the gender guess more reliable. <a href="/accuracy/">Research has not found this method more reliable than chance.</a> A different result on another website can come from another chart version, age convention or leap-month rule.</p>
<h2>Calendar sources and chart rules</h2><p>Dates are generated with <a href="${lunar}">lunar-javascript</a> and checked against the <a href="https://www.hko.gov.hk/en/gts/time/calendar/text/files/T${year}e.txt">Hong Kong Observatory’s ${year} conversion table</a>. Our <a href="/how-it-works/#chart-source">method page</a> identifies the chart version and explains the leap-month convention. These sources do not endorse the gender-prediction claim.</p>`);}
export function methodPage(){return article('How the Chinese Gender Predictor Works','Every result comes from two chart coordinates: lunar age and lunar month. Here is how we get them, and where the tradition has limitations.',`
<h2>One traditional tool, several names</h2><p>Chinese gender predictor, Chinese gender calendar and Chinese birth chart often refer to this same folklore lookup. Here, “birth chart” means the age-and-month table, not an astrological chart based on a birth time. The calculator and printable calendars all use the same table.</p>
<h2>Start with regular calendar dates</h2><p>Enter the mother’s date of birth and an estimated conception date using the familiar Gregorian calendar. You do not need a lunar birthday, manually adjusted age, or separate Chinese calendar.</p><p>If you know only the due date, choose that option. We subtract 266 calendar days to estimate conception, reflecting the average interval described in the <a href="https://www.msdmanuals.com/home/women-s-health-issues/normal-pregnancy/pregnancy-test-and-due-date">MSD Manual’s explanation of due dates</a>. This does not establish the actual day conception happened.</p>
<h2>Convert to the lunar calendar</h2><p>We use <a href="${lunar}">lunar-javascript</a> to find the lunar year of birth, lunar year of conception and lunar conception month. Inputs are treated as calendar dates without a time of day, so your browser’s time zone does not move a date to the preceding day.</p><p>The converter uses the Chinese calendar represented by the library. Lunar months begin at calendar-defined boundaries and do not line up with Gregorian months. Lunar month 1 is not another name for January.</p>
<h2>Calculate traditional lunar age</h2><p>The convention used here counts one year at birth and adds a year at each Chinese New Year. It uses Chinese New Year, not the solar term known as Start of Spring.</p><div class="note-box"><p class="formula">Conception lunar year − birth lunar year + 1</p><p>This is why “regular age + 1” is not always the same calculation. Check a specific date with the <a href="/lunar-age-calculator/">Chinese lunar age calculator</a>.</p></div>
<h2>A complete example</h2><p>For a birth date of <strong>June 15, 1995</strong> and conception date of <strong>May 1, 2026</strong>:</p><ol><li>The lunar birth year is 1995.</li><li>Conception is lunar year 2026, month 3, day 15.</li><li>Lunar age is 2026 − 1995 + 1 = 32.</li><li>Age 32 and month 3 intersect at “Boy” in this chart.</li></ol><p>This is a worked lookup, not evidence about an actual pregnancy. “Try an example” on the homepage uses these dates. A due date of January 22, 2027 also leads to this example after subtracting 266 days. The relevant reference is the <a href="/chinese-gender-calendar-2026/">2026 conception calendar</a>.</p>
<h2 id="chart-source">Which chart do we use?</h2><p>We use the 18-to-45 age, 12-month matrix from the MIT-licensed <a href="${chart}">bdp-raymon/chinese-gender-prediction project</a>, pinned to revision <code>8c5338d</code>. We reuse its table, not its age-calculation code. <a href="/third-party-notices.txt">License and attribution</a> are included.</p><p>Different versions of this chart circulate. We have not verified claims that any one version is an original imperial or archaeological record. We do not describe it as an official or medically approved chart.</p><p>The same data drives the <a href="/#chinese-gender-chart">visible chart</a> and the calculator. Ages outside the chart range are rejected rather than silently changed to the nearest supported age.</p>
<h2>What happens in a leap month?</h2><p>The Chinese calendar sometimes contains an extra month with the same number as another month. The 12-column chart has no separate leap-month column.</p><p><strong>Our convention:</strong> a leap month uses the column with the matching number. Leap month 6 uses column 6. Results identify the leap month. Other traditional interpretations may use different rules, so calculators can disagree.</p>
<h2>Why we flag uncertain dates</h2><p>If conception is within seven days of a lunar-month boundary, we show a notice. Seven days is a usability reminder, not a medical confidence interval. A small change in your estimate may move the lookup to another cell.</p><p>Dates remain in your browser. No calculation needs an account or remote service. <a href="/privacy/">Read how data is handled.</a></p>
<h2>Conversion is not scientific prediction</h2><p>A repeatable lookup can describe a tradition without scientific predictive value. Our <a href="/accuracy/">accuracy guide</a> separates the calendar calculation from the claim it is sometimes used to make.</p><p class="updated">Method and sources checked October 9, 2026.</p>`);}
export function accuracyPage(){return article('Is the Chinese Gender Predictor Accurate?','It is a traditional guessing game. There is no good evidence that the Chinese gender calendar predicts a baby’s sex better than chance.',`
<h2>What the research found</h2><p>A 2010 study by Eduardo Villamor and colleagues tested the Chinese lunar calendar method using <strong>2,840,755 singleton births</strong> in Sweden between 1973 and 2006. The researchers found essentially no predictive agreement beyond chance.</p><p>Their conclusion was that it was no better than tossing a coin. Read the <a href="${study}">original study abstract on PubMed</a> or the paper through <a href="https://doi.org/10.1111/j.1365-3016.2010.01129.x">DOI 10.1111/j.1365-3016.2010.01129.x</a>.</p><div class="note-box"><p><strong>What this means for your result:</strong> “Boy” or “Girl” here is the output of a traditional chart. It is not a diagnosis, a test result or an individualized probability.</p></div>
<h2>A more recent study</h2><p>A 2023 study at Koru Ankara Hospital in Turkey included <strong>17,580 singleton births</strong>. It reported a kappa statistic of 0.002 and a p-value of 0.797, finding no meaningful agreement beyond chance between the calendar guesses and recorded sex at birth. Read the <a href="${recentStudy}">original paper in Actual Gynecology and Obstetrics</a>.</p><p>This was a retrospective study from one hospital. It estimated conception by adding 14 days to the recorded last menstrual period; that approximation can introduce error. It does not validate every circulating chart or prove what will happen in an individual pregnancy. Together, the studies provide no support for a reliable prediction claim.</p>
<h2>Can a Chinese gender predictor be 100% accurate?</h2><p>No evidence supports a 100% accuracy claim for this traditional chart. A match with one pregnancy is not a guarantee for the next. A free calculator, a paid chart and a printable PDF have the same underlying limitation.</p>
<h2>Why can it seem to work?</h2><p>A chart with two result labels will sometimes match what later happens. One match does not show predictive power. Personal stories cannot tell us how often guesses failed or how the comparison was made.</p><p>Claims such as “90% accurate,” “scientifically proven” or “guaranteed” need strong evidence. We do not make those claims or attach a confidence score to a result.</p>
<h2>Do lunar-date corrections make it reliable?</h2><p>Using lunar age and lunar month makes the calculation consistent with its stated rules. It does not demonstrate that the rules predict biological outcomes. These are different questions:</p><ul><li><strong>Calendar correctness:</strong> were dates converted and the table read consistently?</li><li><strong>Predictive validity:</strong> does the table predict the outcome better than chance?</li></ul><p>We test the first and explain the evidence about the second. Inspect the <a href="/how-it-works/">full method and chart source</a>.</p>
<h2>Why did another website give a different answer?</h2><p>Chart versions, regular versus lunar age, approximate conception dates and leap-month conventions can all affect a lookup. Treat disagreements as another reason to approach this as folklore, rather than trying repeatedly for a preferred answer.</p>
<h2>For questions about your pregnancy</h2><p>Use a qualified healthcare professional for decisions about pregnancy, screening and test interpretation. This website does not assess a pregnancy or recommend medical procedures. Do not use its results for health decisions or to plan a child’s sex.</p><p>The common search term “gender predictor” names this traditional tool. Its boy/girl guesses do not tell you a child’s future gender identity.</p>
<h2>Research references</h2><p class="source-list">Villamor E, Dekker L, Svensson T, Cnattingius S. <em>Accuracy of the Chinese lunar calendar method to predict a baby’s sex: a population-based study.</em> Paediatric and Perinatal Epidemiology, 2010. <a href="${study}">PMID: 20618730</a>.</p><p class="source-list">Jafarzade A, Aghayeva S, Mungan TM, Biri A, Ekiz OU. <em>Predicting Baby Gender Using the Chinese Lunar Calendar.</em> Actual Gyn. 2023;15:57-60. <a href="${recentStudy}">Read the full paper (PDF)</a>.</p><p class="updated">This page has not been reviewed or endorsed by a medical professional.</p>`);}
export function aboutPage(){return article('About this little tradition','A free, independent tool for exploring the Chinese gender calendar, with the calculation and its limitations in plain sight.',`
<h2>What this website is for</h2><p>Chinese Gender Predictor turns a traditional chart into a browser-based experience. Make a playful guess, look up your lunar age, or see how a Gregorian date maps to the Chinese calendar.</p><p>We aim to make a folklore activity understandable. We do not offer medical predictions, suggest ways to influence a baby’s sex, or claim scientific authority for the chart.</p>
<h2>Our approach</h2><ul><li><strong>Show the calculation.</strong> Include lunar age, month and the date used.</li><li><strong>Name assumptions.</strong> Explain due-date estimates and leap-month choices.</li><li><strong>Keep dates local.</strong> No input dates are sent to a server.</li><li><strong>Link to evidence.</strong> Scientific claims link to research, not testimonials.</li></ul>
<h2>Made for a little curiosity</h2><p>You can browse the <a href="/chinese-gender-calendar-2026/">2026</a> and <a href="/chinese-gender-calendar-2027/">2027 printable calendars</a> or use our <a href="/gender-reveal-games/">free printable gender reveal games</a> at a gathering. The games invite guests to make guesses; they do not establish information about a pregnancy.</p>
<h2>Sources and attribution</h2><p>The matrix comes from a <a href="${chart}">published MIT-licensed chart implementation</a>. Conversion uses <a href="${lunar}">lunar-javascript</a>, with representative dates checked against <a href="${hko}">Hong Kong Observatory tables</a>. Our accuracy explanation cites <a href="${study}">the 2010 population study</a> and <a href="${recentStudy}">a 2023 hospital study</a>.</p><p>These sources are references, not sponsors or endorsements. Read the <a href="/third-party-notices.txt">software and font attributions</a>. The nursery mobile illustration was created for this website using an image-generation tool.</p>
<h2>Corrections and contact</h2><p>This independent project is maintained by <a href="https://github.com/BogerHou">BogerHou</a>. For a reproducible bug or source correction, <a href="https://github.com/BogerHou/chinesegenderpredictor/issues">open an issue in the public project repository</a>. Please do not include personal birth dates or pregnancy information in public issues.</p>
<h2>Editorial boundaries</h2><p>We have not established an authoritative historical origin for this chart. We do not use invented medical reviewers, accuracy ratings or testimonials. The <a href="/how-it-works/">method page</a> identifies the version so results can be reproduced.</p><p>When we correct calculations or update sources, we update the relevant explanation and review date. If something looks inconsistent, the visible table and linked source let you compare the result directly.</p><p class="updated">Last updated October 9, 2026.</p>`);}
export function privacyPage(){return article('Your dates stay with you','The calculator runs in your browser. This page describes how the current version handles data.',`
<h2>Calculator inputs</h2><p>Birth dates, conception dates, due dates and results are processed locally. We do not transmit them to a calculation service, include them in URLs, or store them in a database. There is no account or calculator-history feature.</p><p>Your browser may retain form values through its own history or autofill behavior. “Start over” clears the page’s inputs. We do not control data retained by your browser or device.</p>
<h2>Sharing and printing</h2><p>“Copy result” copies the boy/girl guess, an entertainment notice and the website address. It does not include dates or lunar age. You decide where to paste it. Printing uses your browser; a selected chart cell may remain highlighted on a printed chart.</p>
<h2>Printable downloads</h2><p>The calendar and game PDFs can be downloaded without an account or email address. The files are blank references and activities; we do not fill them with your calculator dates. Any details you write on a printed game card stay on that card.</p>
<h2>Hosting and technical requests</h2><p>Loading any website sends network information, including your IP address and requested page, to its host. Our hosting provider is Vercel. See <a href="https://vercel.com/legal/privacy-policy">Vercel’s privacy policy</a> for hosting-related information.</p><p>Fonts, images and code are served from this website. This version has no advertising scripts, analytics scripts, third-party font requests, tracking cookies or embedded social widgets.</p>
<h2>External links</h2><p>Research and reference links lead to services with their own policies. Your calculator dates are not attached to those links.</p><p class="updated">Last updated October 9, 2026.</p>`);}
export function termsPage(){return article('Terms of use','The purpose and limits of this traditional entertainment tool.',`
<h2>For entertainment</h2><p>This site provides a Chinese gender-chart lookup and calendar information for general interest and entertainment. It is not a medical service and does not predict a baby’s sex with scientifically established accuracy.</p><p>Do not rely on it for healthcare, reproductive or other consequential decisions. Direct pregnancy and medical questions to a qualified professional.</p>
<h2>Calculation limits</h2><p>We document the calendar convention, chart version and leap-month rule used here. Other charts may disagree. Due-date calculations estimate conception, and calendar data may contain limitations or errors.</p><p>The chart supports lunar ages 18 to 45. The date converter supports years 1900 to 2099. An unsupported result is not filled in or inferred.</p>
<h2>Using the content</h2><p>You may use the tool and print the chart for personal reference. Our original party-game printables are free for personal, noncommercial events. You may print copies for your guests; please link to the download page rather than selling, repackaging or redistributing the PDF files. Third-party software and chart data retain their <a href="/third-party-notices.txt">licenses and attribution notices</a>.</p>
<h2>Availability and updates</h2><p>The site may change as its implementation or sources are updated. We do not promise continuous availability or a particular outcome. Our <a href="/privacy/">privacy page</a> explains the current data handling.</p><p class="updated">Last updated October 9, 2026.</p>`);}
export function gamesPage(){return article('Free Printable Gender Reveal Games','Three easy activities for a little friendly guessing: prediction cards, a team vote sheet and a baby-name race. Download the complete set in A4 or US Letter.',`
<div class="download-box" id="download"><h2>Your printable game pack</h2><p>The free three-page PDF includes four cut-out prediction cards, one vote sheet for 20 guests and an A-Z baby-name race. No email or account is required. Print extra copies for a larger party.</p><div class="download-actions"><a class="button primary small" href="/downloads/gender-reveal-games-a4.pdf" download>${icon('download-simple')}Download A4 games</a><a class="button secondary small" href="/downloads/gender-reveal-games-letter.pdf" download>${icon('download-simple')}Download US Letter games</a></div><p class="small-copy">You will need paper, pens, scissors for the cards, and a timer for the name race. Print at 100% or actual size; the text and checkboxes work in color or black and white.</p></div>
<div class="note-box"><p><strong>Keep guesses separate from the announcement.</strong> These activities are for fun. Guests can choose “Surprise” instead of making a boy/girl guess. The Chinese gender chart cannot supply a confirmed reveal result; use only information the parents have chosen to share.</p></div>
<h2 id="prediction-cards">1. Make a little guess: prediction cards</h2><p><strong>Players:</strong> any number, one card each. <strong>Time:</strong> 3 to 5 minutes. <strong>Print:</strong> page 1, with four cards per sheet.</p><figure class="game-preview"><img src="/assets/games-prediction-cards-preview.png" alt="Preview of four printable prediction cards with a guest name, Boy, Girl or Surprise choice, and a message for the family." width="540" height="764" loading="lazy"><figcaption>Four small cards to cut out and keep as party keepsakes.</figcaption></figure><ol><li>Cut out the cards before guests arrive and set them beside a cup of pens.</li><li>Each guest adds a name, marks Boy, Girl or Surprise, and optionally writes a short message for the family.</li><li>Collect the cards in a bowl or display them together. After the parents share their announcement, invite guests to compare their guesses.</li></ol><p>There is no need to name a winner. The messages can become the most memorable part. For a remote gathering, guests can print a card at home and read their message aloud.</p>
<h2 id="team-vote">2. Team vote sheet</h2><p><strong>Players:</strong> up to 20 per sheet. <strong>Time:</strong> about 5 minutes across guest arrival. <strong>Print:</strong> page 2, one shared sheet for every 20 guests.</p><figure class="game-preview"><img src="/assets/games-vote-sheet-preview.png" alt="Preview of a guest vote sheet with 20 rows, Boy, Girl and Surprise columns, and spaces for the totals." width="540" height="764" loading="lazy"><figcaption>One shared sheet makes it easy to count the room’s guesses.</figcaption></figure><ol><li>Place the sheet where everyone can reach it. Each guest writes a name and marks exactly one choice.</li><li>Close voting before the announcement. Count the marks in each column and write the totals at the bottom.</li><li>Read the totals aloud if the parents want to. Keep the Surprise votes in the tally so guests can join without choosing a side.</li></ol><p>These are guest votes, not probabilities. If you use multiple sheets, add their totals together. Voting does not require sharing birth dates, due dates or any medical information.</p>
<h2 id="baby-name-race">3. The A-Z baby-name race</h2><p><strong>Players:</strong> 2 or more, individually or in pairs. <strong>Time:</strong> 3 minutes of play, plus time to compare. <strong>Print:</strong> page 3, one sheet per player or pair.</p><figure class="game-preview"><img src="/assets/games-name-race-preview.png" alt="Preview of an A to Z baby-name race sheet with a writing line for each letter and a total score." width="540" height="764" loading="lazy"><figcaption>A quick word game that works before or after the announcement.</figcaption></figure><ol><li>Give everyone a sheet and agree to use first names starting with the letters A to Z. Names can be for any gender.</li><li>Set a timer for 3 minutes. Write one name beside as many letters as possible.</li><li>Award one point for each completed letter with a name the group recognizes. The maximum score is 26. Players with the same score share the win.</li></ol><p>For younger guests, pair them with an adult or skip the timer. For a quieter game, let everyone work together to fill one sheet. The names are suggestions for fun; the parents do not need to choose from the answers.</p>
<h2>A simple party order</h2><ol><li><strong>As guests arrive:</strong> leave prediction cards and the vote sheet beside the welcome table.</li><li><strong>When everyone is settled:</strong> play the name race.</li><li><strong>Before the announcement:</strong> collect cards and close voting.</li><li><strong>Afterward:</strong> share messages and keep the cards as a small memento.</li></ol>
<h2>Add the Chinese chart as one extra guess</h2><p>If the parents would enjoy it, they can privately use the <a href="/">Chinese gender predictor</a> and share only the chart’s Boy or Girl guess. There is no need to show their dates to guests. The <a href="/chinese-gender-calendar-2026/">2026</a> and <a href="/chinese-gender-calendar-2027/">2027 printable calendars</a> explain the lookup for anyone curious about the tradition.</p><p>The chart is an entertainment activity, and <a href="/accuracy/">research does not support it as a reliable prediction</a>. A party announcement should not be based on the chart.</p>
<h2>Printing and permission</h2><p>These three game layouts were created for Chinese Gender Predictor. You may print them for personal, noncommercial events, including copies for your guests. Please share a link to this page instead of redistributing or selling the files. Keep the source credit on your copies.</p><p>Select the PDF that matches your paper: A4 is 210 × 297 mm; US Letter is 8.5 × 11 inches. Turn off double-sided printing for the card sheet, and print one test page before making the full set. <a href="/terms/">Read the terms of use.</a></p>`);}
export const pages={'/lunar-age-calculator/':agePage,'/chinese-gender-calendar-2026/':()=>yearPage(2026),'/chinese-gender-calendar-2027/':()=>yearPage(2027),'/gender-reveal-games/':gamesPage,'/how-it-works/':methodPage,'/accuracy/':accuracyPage,'/about/':aboutPage,'/privacy/':privacyPage,'/terms/':termsPage};
