import {esc,form,resultPanel,icon,chartTable} from './templates.mjs';
import {calendarMonths,lunarDate,lunarAge} from './calendar.mjs';
import {gamesBody} from './games-content.mjs';
import {oldWivesTalesBody} from './old-wives-tales.mjs';
const study='https://pubmed.ncbi.nlm.nih.gov/20618730/';
const recentStudy='https://www.actualgyn.com/pdf/en_2023_281.pdf';
const chart='https://github.com/bdp-raymon/chinese-gender-prediction/blob/8c5338d043a85ad3b4de2af0dd516bd6c7d2b62b/src/calendar.php';
const lunar='https://github.com/6tail/lunar-javascript';
const hko='https://www.hko.gov.hk/en/gts/time/conversion.htm';
const dateLabel=value=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));
function editorial(){return `<p class="editorial-meta">By <a href="/about/">BogerHou</a> · Updated October 9, 2026</p>`;}
const guideLinks={
  '/lunar-age-calculator/':'Calculate your lunar age',
  '/chinese-gender-calendar-2026/':'2026 calendar & printable chart',
  '/chinese-gender-calendar-2027/':'2027 calendar & printable chart',
  '/how-it-works/':'How the chart works',
  '/accuracy/':'What the research says',
  '/gender-reveal-games/':'Free printable party games',
  '/old-wives-tales-gender-prediction/':'Other folklore guesses',
  '/about/':'About & sources',
  '/privacy/':'Your dates and privacy',
  '/terms/':'Terms of use'
};
const relatedGuides={
  '/lunar-age-calculator/':['/how-it-works/','/chinese-gender-calendar-2027/','/accuracy/'],
  '/chinese-gender-calendar-2026/':['/chinese-gender-calendar-2027/','/lunar-age-calculator/','/how-it-works/'],
  '/chinese-gender-calendar-2027/':['/chinese-gender-calendar-2026/','/lunar-age-calculator/','/how-it-works/'],
  '/how-it-works/':['/lunar-age-calculator/','/chinese-gender-calendar-2027/','/accuracy/'],
  '/accuracy/':['/how-it-works/','/old-wives-tales-gender-prediction/','/about/'],
  '/gender-reveal-games/':['/old-wives-tales-gender-prediction/','/chinese-gender-calendar-2027/','/accuracy/'],
  '/old-wives-tales-gender-prediction/':['/gender-reveal-games/','/accuracy/','/how-it-works/'],
  '/about/':['/how-it-works/','/accuracy/','/privacy/'],
  '/privacy/':['/about/','/terms/','/how-it-works/'],
  '/terms/':['/privacy/','/about/','/gender-reveal-games/']
};
function guideContent(content){
  const used=new Set([...content.matchAll(/\bid=["']([^"']+)["']/g)].map(match=>match[1]));
  const headings=[];
  const html=content.replace(/<h2\b([^>]*)>([\s\S]*?)<\/h2>/g,(whole,attributes,inner)=>{
    const label=inner.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').trim();
    let id=attributes.match(/\bid=["']([^"']+)["']/)?.[1];
    if(!id){
      const stem=label.normalize('NFKD').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'section';
      id=stem;let suffix=2;
      while(used.has(id))id=`${stem}-${suffix++}`;
      used.add(id);attributes+=` id="${id}"`;
    }
    headings.push({id,label});
    return `<h2${attributes}>${inner}</h2>`;
  });
  return {html,headings};
}
function aside(path,headings){
  const related=(relatedGuides[path]||['/how-it-works/','/accuracy/','/gender-reveal-games/']).filter(href=>href!==path).slice(0,3);
  return `<aside class="article-aside"><nav class="guide-toc" aria-label="On this page"><h2 class="guide-toc-title">On this page</h2><ol class="guide-toc-list">${headings.map(({id,label},index)=>`<li><a href="#${esc(id)}"><span class="guide-toc-number" aria-hidden="true">${String(index+1).padStart(2,'0')}</span><span>${esc(label)}</span></a></li>`).join('')}</ol></nav><div class="guide-related"><h2>Read next</h2>${related.map(href=>`<a href="${href}">${guideLinks[href]}</a>`).join('')}</div><a class="button primary" href="/">Open predictor</a></aside>`;
}
function article(title,description,content,path){const guide=guideContent(content);return `<section class="container article-section"><div class="breadcrumb"><a href="/">Home</a> / ${esc(title)}</div><header class="article-header"><h1>${title}</h1><p>${description}</p>${editorial()}</header><div class="article-layout">${aside(path,guide.headings)}<article class="prose">${guide.html}</article></div></section>`;}
function ageComparison(){
  const birth='2000-06-01';
  const dates=['2026-02-16','2026-02-17','2026-06-01'];
  return `<div class="table-wrap" tabindex="0" role="region" aria-label="Gregorian and lunar age comparison"><table class="month-table"><caption>Age on three dates for a June 1, 2000 birthday</caption><thead><tr><th scope="col">Target date</th><th scope="col">Regular age</th><th scope="col">Traditional lunar age</th></tr></thead><tbody>${dates.map(value=>{const age=lunarAge(birth,value);return `<tr><th scope="row">${dateLabel(value)}</th><td>${age.gregorianAge}</td><td>${age.age}</td></tr>`;}).join('')}</tbody></table></div>`;
}
export function agePage(){const guide=guideContent(`
<h2 id="my-lunar-age">What is my lunar age?</h2><p>Enter your date of birth and the date you want to check in the calculator above. For your age today, select today as the target date. For the Chinese gender chart, select your estimated conception date.</p><p>If you only know your due date, use the <a href="/#predictor">gender predictor’s Due date option</a>. It estimates conception first; entering the due date itself here would calculate your age on a different day.</p>
<h2 id="what-is-lunar-age">What is a lunar age?</h2><p>Lunar age is a traditional Chinese way of counting age, sometimes called <em>xu sui</em>. You start at one at birth and add a year at each Chinese New Year. Your regular age, by comparison, increases on your birthday.</p><div class="note-box"><p class="formula">Lunar age = target lunar year − birth lunar year + 1</p></div><p>The important detail is <em>lunar year</em>. A birthday in January or early February may belong to the preceding lunar year. Simply adding one to your regular age can give the wrong answer.</p>
<h2>Why lunar age can be one or two years higher</h2><p>Consider someone born on June 1, 2000. Their Gregorian age changes on June 1; their traditional age changes at Chinese New Year.</p>${ageComparison()}<p>In this example, February 17 is Chinese New Year. The lunar count increases while the Gregorian age stays the same. This is why adding one is not a reliable substitute for converting both dates.</p><p>For a February 29 birth, the Gregorian comparison in this tool advances on March 1 in non-leap years. The traditional lunar-age count still changes at Chinese New Year.</p>
<h2>Using this age with the gender chart</h2><p>The traditional gender chart uses age at <strong>conception</strong>. Choose that date here if you are looking up the chart manually. The <a href="/#predictor">Chinese gender predictor</a> performs this conversion automatically and also finds the <a href="/how-it-works/#lunar-month-of-conception">lunar month of conception</a>.</p><p>Knowing your lunar age helps you read the traditional chart. It does not make the chart’s gender guess more reliable. <a href="/accuracy/#calendar-accuracy">Read the evidence on prediction accuracy.</a></p>
<h2>Dates and limits</h2><p>You can check dates from 1900 to 2099. The gender chart covers lunar ages 18 to 45, but this age calculator also works outside that range. Calendars may differ on some dates far in the future.</p><p class="source-list">Calendar references: <a href="${hko}">Hong Kong Observatory conversion tables</a> and the <a href="${lunar}">date-conversion source</a>.</p>`);return `<section class="container article-section age-tool"><div class="breadcrumb"><a href="/">Home</a> / Lunar age calculator</div><header class="article-header"><h1>Lunar Age Calculator</h1><p>Find your traditional Chinese age on any date and compare it with your regular age.</p>${editorial()}</header><div class="tool-grid">${form({ageOnly:true})}${resultPanel({ageOnly:true})}</div><div class="article-layout">${aside('/lunar-age-calculator/',guide.headings)}<article class="prose">${guide.html}</article></div></section>`;}
function conceptionExamples(){
  const dates=['2026-05-16','2026-05-17','2027-02-05','2027-02-06'];
  return `<div class="table-wrap" tabindex="0" role="region" aria-label="Examples of Gregorian to lunar conception dates"><table class="month-table"><caption>Dates when the lunar month changes</caption><thead><tr><th scope="col">Gregorian date</th><th scope="col">Lunar date</th><th scope="col">Chart column</th></tr></thead><tbody>${dates.map(value=>{const lunar=lunarDate(value);return `<tr><th scope="row">${dateLabel(value)}</th><td>${lunar.year}, month ${lunar.month}, day ${lunar.day}</td><td>${lunar.month}</td></tr>`;}).join('')}</tbody></table></div>`;
}
const yearDetails={
  2026:{newYear:'February 17, 2026',previousEnd:'February 16',partial:'Lunar month 11 of 2025 starts in December 2025; lunar month 11 of 2026 continues into January 2027.',boundary:'February 16, 2026 is in lunar year 2025, month 12. February 17 is in lunar year 2026, month 1.',example:'For a mother born June 15, 1995, conception on May 1, 2026 falls in lunar year 2026, month 3. Her lunar age is 32, and row 32, column 3 reads Boy in this chart.'},
  2027:{newYear:'February 6, 2027',previousEnd:'February 5',partial:'Lunar month 11 of 2026 starts in December 2026; lunar month 12 of 2027 continues into January 2028.',boundary:'February 5, 2027 is in lunar year 2026, month 12. February 6 is in lunar year 2027, month 1.',example:'For a mother born June 15, 1995, conception on February 5, 2027 uses lunar age 32 and month 12. Conception on February 6 uses lunar age 33 and month 1. Both her lunar age and lunar month change at Chinese New Year.'}
};
export function yearPage(year=2027){const months=calendarMonths(year),detail=yearDetails[year];return article(`Chinese Gender Calendar ${year}`,`Find the lunar month for a conception date in ${year}, read the complete traditional gender chart, or download a free printable PDF.`,`
<nav class="year-nav" aria-label="Calendar year"><a href="/chinese-gender-calendar-2026/"${year===2026?' aria-current="page"':''}>2026 calendar</a><a href="/chinese-gender-calendar-2027/"${year===2027?' aria-current="page"':''}>2027 calendar</a></nav>
<div class="note-box"><p><strong>Chinese New Year is ${detail.newYear}.</strong> January 1 through ${detail.previousEnd} still belongs to lunar year ${year-1}. The chart uses your age and month at conception, even if the baby is due in another year.</p></div>
${year===2027?`<h2>Use the Chinese gender predictor for 2027</h2><p>To use the Chinese calendar for a baby gender guess in 2027, start with the estimated conception date. The calculator converts your birth date and that date to the lunar age and month used in this chart. If you know only the due date, choose its Due date option.</p><p><a class="button primary small" href="/#predictor">Calculate with your 2027 dates</a></p>`:''}
<div class="download-box" id="download"><h2>Download the ${year} calendar PDF</h2><p>This two-page PDF keeps the full chart, Gregorian-to-lunar month dates, lookup instructions and source notes together. Choose your paper size and print at actual size or 100% scale.</p><div class="download-actions"><a class="button secondary small" href="/downloads/chinese-gender-calendar-${year}-a4.pdf" download>${icon('download-simple')}Download A4 PDF</a><a class="button secondary small" href="/downloads/chinese-gender-calendar-${year}-letter.pdf" download>${icon('download-simple')}Download US Letter PDF</a></div><p class="small-copy">Free for personal reference. The traditional chart is for entertainment, not a medical prediction.</p></div>
<h2 id="lunar-months">Find the lunar month for your date</h2><p>Use the <strong>estimated conception date</strong>, not the due date. This table shows the part of each lunar month that falls within Gregorian year ${year}. The first and last rows are partial months.</p>
<div class="table-wrap" tabindex="0" role="region" aria-label="${year} Gregorian to lunar month reference"><table class="month-table"><caption>Lunar months within Gregorian year ${year}</caption><thead><tr><th scope="col">Gregorian dates (inclusive)</th><th scope="col">Lunar year</th><th scope="col">Lunar month</th></tr></thead><tbody>${months.map((m,i)=>`<tr><td>${dateLabel(m.start)} to ${dateLabel(m.end)}${i===0||i===months.length-1?' *':''}</td><td>${m.year}</td><td>${m.leap?'Leap ':''}${m.month}</td></tr>`).join('')}</tbody></table></div>
<p class="small-copy">* Only days within ${year} are shown. ${detail.partial} There is no leap lunar month within Gregorian year ${year}.</p>
<h2 id="chinese-gender-chart">The complete ${year} Chinese gender chart</h2><p>The traditional chart is the same each year. Use the lunar dates above to find the right month column. Find the mother’s <a href="/lunar-age-calculator/">lunar age at conception</a> in rows 18 to 45, then read across to the lunar month. B means Boy and G means Girl.</p>${chartTable()}
<h2>How to use the calendar</h2><ol><li>Find your estimated conception date in the month table above.</li><li>Calculate your lunar age on that date. The count is one at birth, then increases at each Chinese New Year.</li><li>Read the chart cell where that age and lunar month meet.</li></ol><p>${detail.example} These sample dates show how to read the chart; they are not a medical prediction. The <a href="/">Chinese gender predictor</a> converts both dates automatically and explains the result.</p>
<h2>Why Chinese New Year matters</h2><p>${detail.boundary} The traditional age count also increases at that boundary. A one-day change here affects both the age row and the month column. Do not substitute January 1 for Chinese New Year or use a regular age without converting it.</p>
<h2 id="due-date">Due in 2027? You may need the 2026 calendar</h2><p>Choose the calendar for the <strong>estimated conception year</strong>. For example, a due date of January 22, 2027 gives an estimated conception date of May 1, 2026 when we subtract 266 days. That lookup uses lunar month 3 of 2026, not the month of birth in 2027.</p><p>This subtraction is an approximation, not a way to identify the actual conception day. If you only know the due date, the <a href="/">calculator’s Due date option</a> handles the estimate. You can compare the <a href="/chinese-gender-calendar-2026/">2026 month dates</a> and <a href="/chinese-gender-calendar-2027/">2027 month dates</a> here.</p>
<h2>Does a year-specific chart improve accuracy?</h2><p>It helps you look up the right lunar dates. It does not make the gender guess more reliable. <a href="/accuracy/">Research has not found this method more reliable than chance.</a> A different result on another website can come from another chart version, age convention or leap-month rule.</p>
<h2>Calendar sources and chart rules</h2><p>The month dates are checked against the <a href="https://www.hko.gov.hk/en/gts/time/calendar/text/files/T${year}e.txt">Hong Kong Observatory’s ${year} conversion table</a>. You can also read <a href="/how-it-works/#chart-source">which gender chart we use</a> and how we handle leap months. The calendar references verify dates, not the gender guess.</p>`, `/chinese-gender-calendar-${year}/`);}
export function methodPage(){return article('How the Chinese Gender Predictor Works','The traditional chart combines the mother’s lunar age with the lunar month of conception. Learn how to find both and read the chart.',`
<h2>One traditional tool, several names</h2><p>Chinese gender predictor, Chinese gender calendar and Chinese birth chart often refer to this same folklore lookup. Here, “birth chart” means the age-and-month table, not an astrological chart based on a birth time. The calculator and printable calendars all use the same table.</p>
<h2>Start with regular calendar dates</h2><p>Enter the mother’s date of birth and an estimated conception date using the familiar Gregorian calendar. You do not need a lunar birthday, manually adjusted age, or separate Chinese calendar.</p><p>If you know only the due date, choose that option. We subtract 266 calendar days to estimate conception, reflecting the average interval described in the <a href="https://www.msdmanuals.com/home/women-s-health-issues/normal-pregnancy/pregnancy-test-and-due-date">MSD Manual’s explanation of due dates</a>. This does not establish the actual day conception happened.</p>
<h2>Find your lunar dates</h2><p>The calculator finds your lunar birth year and the lunar year and month of conception from the dates you enter. You can use your usual calendar dates; no manual conversion is needed.</p><p>Chinese lunar months start on different dates from regular calendar months. Lunar month 1 is not the same as January, so the exact conception date matters.</p>
<h3 id="lunar-month-of-conception">Find the lunar month of conception</h3><p>The lunar month of conception is the Chinese-calendar month containing your estimated conception date. Convert the exact date rather than treating a Gregorian month number as a lunar month number.</p>${conceptionExamples()}<p>The first pair crosses a lunar-month boundary within May. The second crosses Chinese New Year, when the lunar-age count also increases. Check the full <a href="/chinese-gender-calendar-2026/#lunar-months">2026</a> or <a href="/chinese-gender-calendar-2027/#lunar-months">2027 lunar-month dates</a> for other conception dates.</p><p class="source-list">Date examples checked against the Hong Kong Observatory’s <a href="https://www.hko.gov.hk/en/gts/time/calendar/text/files/T2026e.txt">2026</a> and <a href="https://www.hko.gov.hk/en/gts/time/calendar/text/files/T2027e.txt">2027 conversion tables</a>.</p>
<h2>Calculate traditional lunar age</h2><p>Your traditional lunar age starts at one at birth and increases at each Chinese New Year. In this calculator, the age changes at Chinese New Year rather than Start of Spring, a date used in some other traditions.</p><div class="note-box"><p class="formula">Conception lunar year − birth lunar year + 1</p><p>This is why “regular age + 1” is not always the same calculation. Check a specific date with the <a href="/lunar-age-calculator/">Chinese lunar age calculator</a>.</p></div>
<h2>A complete example</h2><p>For a birth date of <strong>June 15, 1995</strong> and conception date of <strong>May 1, 2026</strong>:</p><ol><li>The lunar birth year is 1995.</li><li>Conception is lunar year 2026, month 3, day 15.</li><li>Lunar age is 2026 − 1995 + 1 = 32.</li><li>Age 32 and month 3 intersect at “Boy” in this chart.</li></ol><p>These sample dates show how the chart works; the guess is not a medical prediction. “Try an example” on the homepage uses these dates. A due date of January 22, 2027 also leads to this example after subtracting 266 days. The relevant reference is the <a href="/chinese-gender-calendar-2026/">2026 conception calendar</a>.</p>
<h2 id="chart-source">Which chart do we use?</h2><p>The chart covers lunar ages 18 to 45 and months 1 to 12. You can compare the <a href="${chart}">published source chart</a> with the <a href="/#chinese-gender-chart">chart on this website</a>. The calculator and printable calendars use that same chart. <a href="/third-party-notices.txt">Source credit and license</a> are available.</p><p>Several versions of the Chinese gender chart exist. Its historical origin is uncertain, and no version should be treated as an official or medically approved prediction.</p><p>If your lunar age is outside 18 to 45, the calculator lets you know instead of giving a guess from another age row.</p>
<h2>What happens in a leap month?</h2><p>The Chinese calendar sometimes contains an extra month with the same number as another month. The 12-column chart has no separate leap-month column.</p><p><strong>Our convention:</strong> a leap month uses the column with the matching number. Leap month 6 uses column 6. Results identify the leap month. Other traditional interpretations may use different rules, so calculators can disagree.</p>
<h2>When a small date change matters</h2><p>If your estimated conception date falls within seven days of a lunar month’s start or end, a reminder appears with your result. Even a small change in the date may lead to a different chart guess. The reminder does not measure how certain your conception date is.</p><p>No account is needed, and your dates stay on your device. <a href="/privacy/">Read about your privacy.</a></p>
<h2>How much should you trust the guess?</h2><p>Correct lunar dates help you read the chart, but they do not make it a reliable prediction. Keep the result as a playful guess. Our <a href="/accuracy/">accuracy guide</a> explains what the research found.</p><p class="updated">Method and sources checked October 9, 2026.</p>`, '/how-it-works/');}
export function accuracyPage(){return article('Is the Chinese Gender Predictor Accurate?','It is a traditional guessing game. There is no good evidence that the Chinese gender calendar predicts a baby’s sex better than chance.',`
<h2 id="calendar-accuracy">How accurate is the Chinese gender calendar?</h2><p>Research does not support the calendar as a reliable way to predict a baby’s sex. A correct lunar-date conversion makes the lookup consistent; it does not make a result medically reliable.</p><h3>What the research found</h3><p>A 2010 study by Eduardo Villamor and colleagues tested the Chinese lunar calendar method using <strong>2,840,755 singleton births</strong> in Sweden between 1973 and 2006. The researchers found essentially no predictive agreement beyond chance.</p><p>Their conclusion was that it was no better than tossing a coin. Read the <a href="${study}">original study abstract on PubMed</a> or the paper through <a href="https://doi.org/10.1111/j.1365-3016.2010.01129.x">DOI 10.1111/j.1365-3016.2010.01129.x</a>.</p><div class="note-box"><p><strong>What this means for your result:</strong> “Boy” or “Girl” is a traditional chart’s guess. It is not a medical result or a measure of your baby’s chances.</p></div>
<h2>A more recent study</h2><p>A 2023 study at Koru Ankara Hospital in Turkey included <strong>17,580 singleton births</strong>. It found no meaningful agreement beyond chance between the calendar guesses and recorded sex at birth. Read the <a href="${recentStudy}">original paper in Actual Gynecology and Obstetrics</a>.</p><p>This was a retrospective study from one hospital. It estimated conception by adding 14 days to the recorded last menstrual period; that approximation can introduce error. It does not validate every circulating chart or prove what will happen in an individual pregnancy. Together, the studies provide no support for a reliable prediction claim.</p>
<h2>Can a Chinese gender predictor be 100% accurate?</h2><p>No evidence supports a 100% accuracy claim for this traditional chart. A match with one pregnancy is not a guarantee for the next. A free calculator, a paid chart and a printable PDF have the same underlying limitation.</p>
<h2>Why can it seem to work?</h2><p>A chart with two result labels will sometimes match what later happens. One match does not show predictive power. Personal stories cannot tell us how often guesses failed or how the comparison was made.</p><p>Claims such as “90% accurate,” “scientifically proven” or “guaranteed” need strong evidence. The chart has no scientifically supported accuracy percentage.</p>
<h2>Do lunar-date corrections make it reliable?</h2><p>Lunar age and lunar month help you find the intended place in the chart. They do not make the boy/girl guess more accurate. A calendar can give the right date while a guessing game still gets the answer wrong.</p><p>Read <a href="/how-it-works/">how to use the chart</a> if you want to understand your lunar age and month.</p>
<h2 id="different-results">Why did another website give a different answer?</h2><p>Chart versions, regular versus lunar age, approximate conception dates and leap-month conventions can all affect a lookup. Treat disagreements as another reason to approach this as folklore, rather than trying repeatedly for a preferred answer.</p>
<h2>For questions about your pregnancy</h2><p>Use a qualified healthcare professional for decisions about pregnancy, screening and test interpretation. This website does not assess a pregnancy or recommend medical procedures. Do not use its results for health decisions or to plan a child’s sex.</p><p>The phrase “gender predictor” refers here to traditional boy/girl guesses about sex. It does not tell you a child’s future gender identity.</p>
<p>For other traditional guessing games and their evidence, see our <a href="/old-wives-tales-gender-prediction/">old wives’ tales gender prediction guide</a>.</p><h2>Research references</h2><p class="source-list">Villamor E, Dekker L, Svensson T, Cnattingius S. <em>Accuracy of the Chinese lunar calendar method to predict a baby’s sex: a population-based study.</em> Paediatric and Perinatal Epidemiology, 2010. <a href="${study}">PMID: 20618730</a>.</p><p class="source-list">Jafarzade A, Aghayeva S, Mungan TM, Biri A, Ekiz OU. <em>Predicting Baby Gender Using the Chinese Lunar Calendar.</em> Actual Gyn. 2023;15:57-60. <a href="${recentStudy}">Read the full paper (PDF)</a>.</p><p class="updated">This page has not been reviewed or endorsed by a medical professional.</p>`, '/accuracy/');}
export function aboutPage(){return article('About Chinese Gender Predictor','A free place to explore the Chinese gender calendar, make a playful guess and find printable activities for your gathering.',`
<h2>A little curiosity while you wait</h2><p>Chinese Gender Predictor brings together a traditional guessing chart, a lunar age calculator and free printable party games. Enter your dates for a lighthearted guess, explore the calendar, or choose an activity to share with family and friends.</p><p>The gender chart is folklore, not a medical prediction or a way to influence a baby’s sex.</p>
<h2>What you’ll find here</h2><ul><li><strong>A guess with an explanation.</strong> See the lunar age and month used in your result.</li><li><strong>Help with your dates.</strong> Use an estimated conception date or a due date.</li><li><strong>Private calculations.</strong> Your dates stay on your device, and no account is needed.</li><li><strong>Clear information about accuracy.</strong> Follow links to the original research.</li></ul>
<h2>Calendars and party printables</h2><p>You can browse the <a href="/chinese-gender-calendar-2026/">2026</a> and <a href="/chinese-gender-calendar-2027/">2027 printable calendars</a> or use our <a href="/gender-reveal-games/">free printable gender reveal games</a> at a gathering. The games invite guests to make guesses; they do not establish information about a pregnancy.</p>
<h2>Sources and attribution</h2><p>The <a href="${chart}">published source chart</a> is available to compare with our calendar. Lunar date examples are checked against <a href="${hko}">Hong Kong Observatory tables</a>; the <a href="${lunar}">calendar-conversion source</a> is also available. Our accuracy guide links to <a href="${study}">the 2010 population study</a> and <a href="${recentStudy}">a 2023 hospital study</a>.</p><p>These references do not endorse the chart’s gender guesses. <a href="/third-party-notices.txt">Source credits and licenses</a> are available.</p>
<h2>Corrections and contact</h2><p>This independent project is maintained by <a href="https://github.com/BogerHou">BogerHou</a>. If a result looks wrong or you notice a source error, <a href="https://github.com/BogerHou/chinesegenderpredictor/issues">report it on GitHub</a>. Reports are public, so please leave out personal birth dates and pregnancy information.</p>
<h2>About the tradition</h2><p>Different Chinese gender charts circulate, and their historical origins are uncertain. Our <a href="/how-it-works/">guide to using the chart</a> explains the version used here, including lunar age and leap months.</p><p>The chart is not medically validated. This website has not been reviewed or endorsed by a medical professional. Pages show their update date, and research links let you read the evidence for yourself.</p><p class="updated">Last updated October 9, 2026.</p>`, '/about/');}
export function privacyPage(){return article('Your dates stay with you','Your calculator dates and results stay on your device. Learn what happens when you calculate, share a result or download a printable.',`
<h2>Your dates and results</h2><p>The calculator works on your device. Your birth date, conception date, due date and result are not sent to us or saved in an account. They are not included in page links.</p><p>Your browser may retain form values through its own history or autofill behavior. “Start over” clears the page’s inputs. We do not control data retained by your browser or device.</p>
<h2>Sharing and printing</h2><p>“Copy result” copies the boy/girl guess, an entertainment notice and the website address. It does not include dates or lunar age. You decide where to paste it. Printing uses your browser; a selected chart cell may remain highlighted on a printed chart.</p>
<h2>Printable downloads</h2><p>The calendar and game PDFs can be downloaded without an account or email address. The files are blank references and activities; we do not fill them with your calculator dates. Any details you write on a printed game card stay on that card.</p>
<h2>Website providers and cookies</h2><p>Vercel hosts this website, and Cloudflare delivers and protects its traffic. Loading a page or downloading a file sends network information, including your IP address and the requested URL, through these providers. They may process and retain request logs to operate and secure their services. See <a href="https://vercel.com/legal/privacy-policy">Vercel’s privacy policy</a> and <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare’s privacy policy</a> for their data-handling practices. Calculator dates and results stay in your browser and are not included in these requests.</p><p>This website has no advertising or visitor analytics and does not use tracking cookies. We do not track calculator use or PDF downloads. Fonts and images are loaded from this website. Cloudflare may use security cookies when needed to protect the website.</p>
<h2>External links</h2><p>Research and reference links lead to services with their own policies. Your calculator dates are not attached to those links.</p><p class="updated">Last updated October 9, 2026.</p>`, '/privacy/');}
export function termsPage(){return article('Terms of use','The purpose and limits of this traditional entertainment tool.',`
<h2>For entertainment</h2><p>This site provides a Chinese gender-chart lookup and calendar information for general interest and entertainment. It is not a medical service and does not predict a baby’s sex with scientifically established accuracy.</p><p>Do not rely on it for healthcare, reproductive or other consequential decisions. Direct pregnancy and medical questions to a qualified professional.</p>
<h2>Calculation limits</h2><p>The <a href="/how-it-works/">guide to using the chart</a> explains lunar age, month and leap months. Other charts may give different guesses. Conception dates estimated from a due date are approximate, and calendar dates may contain errors.</p><p>The chart supports lunar ages 18 to 45. The date converter supports years 1900 to 2099. If your dates or age are outside these ranges, the calculator will let you know instead of giving a guess.</p>
<h2>Using the content</h2><p>You may use the tool and print the chart for personal reference. Our original party-game printables are free for personal, noncommercial events. You may print copies for your guests; please link to the download page rather than selling, repackaging or redistributing the PDF files. Third-party software and chart data retain their <a href="/third-party-notices.txt">licenses and attribution notices</a>.</p>
<h2>Availability and updates</h2><p>The website may change as we improve the calculator or update its sources. We do not promise continuous availability or a particular outcome. Our <a href="/privacy/">privacy page</a> explains the current data handling.</p><p class="updated">Last updated October 9, 2026.</p>`, '/terms/');}
export function gamesPage(){return article('5 Free Printable Gender Reveal Games','Choose an activity for your gathering and download the original cards, puzzles and host instructions.',gamesBody(),'/gender-reveal-games/');}
export function oldWivesPage(){return article('Old Wives’ Tales Gender Prediction','Explore eight pregnancy folklore guesses, what the evidence says, and a free printable old wives’ tales gender reveal game.',oldWivesTalesBody(),'/old-wives-tales-gender-prediction/');}
export const pages={'/lunar-age-calculator/':agePage,'/chinese-gender-calendar-2026/':()=>yearPage(2026),'/chinese-gender-calendar-2027/':()=>yearPage(2027),'/gender-reveal-games/':gamesPage,'/old-wives-tales-gender-prediction/':oldWivesPage,'/how-it-works/':methodPage,'/accuracy/':accuracyPage,'/about/':aboutPage,'/privacy/':privacyPage,'/terms/':termsPage};
