import {readFileSync} from 'node:fs';
import {CHART} from './chart.mjs';
export const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(name,extra='') {
  return readFileSync(`node_modules/@phosphor-icons/core/assets/regular/${name}.svg`,'utf8').replace('<svg ',`<svg class="icon ${extra}" aria-hidden="true" focusable="false" `);
}
export const routes = [
  ['/', 'Chinese Gender Predictor | Free Chinese Gender Calendar', 'Try a free Chinese gender predictor with automatic lunar age and month conversion. Explore the traditional chart and see how your result is calculated.'],
  ['/lunar-age-calculator/', 'Lunar Age Calculator | Chinese Age by Date', 'Calculate your traditional Chinese lunar age on any date. See the lunar birth year, target year and the formula behind your result.'],
  ['/chinese-gender-calendar-2027/', 'Chinese Gender Calendar 2027 | Lunar Month Dates', 'Find the 2027 Chinese gender calendar with Gregorian-to-lunar month dates, Chinese New Year boundaries and a printable month reference.'],
  ['/how-it-works/', 'How the Chinese Gender Predictor Works', 'Understand lunar age, conception month, leap months and the traditional chart used by this Chinese gender predictor. See a worked example.'],
  ['/accuracy/', 'Is the Chinese Gender Predictor Accurate? The Evidence', 'What research says about Chinese gender prediction, why calculators can disagree, and the difference between a correct date conversion and a reliable prediction.'],
  ['/about/', 'About Chinese Gender Predictor', 'Our purpose, chart sources, calculation choices and editorial standards for this independent folklore calculator.'],
  ['/privacy/', 'Privacy | Chinese Gender Predictor', 'How this website handles dates and calculations. Inputs stay in your browser and are not included in URLs or analytics.'],
  ['/terms/', 'Terms of Use | Chinese Gender Predictor', 'The Chinese gender predictor is a traditional entertainment tool. Read the scope, limitations and terms for using this website.']
];
export function shell(path,body,{origin='',indexable=false,title,description}={}) {
  const route=routes.find(r=>r[0]===path);
  title ||= route?.[1]||'Page not found | Chinese Gender Predictor'; description ||=route?.[2]||'Find the Chinese gender predictor and our guides.';
  const canonical=origin?new URL(path,origin).href:'';
  const structured = [{ '@context':'https://schema.org','@type':'WebSite',name:'Chinese Gender Predictor',...(origin?{url:origin+'/'}:{}),inLanguage:'en'}];
  if(path==='/')structured.push({'@context':'https://schema.org','@type':'WebApplication',name:'Chinese Gender Predictor',applicationCategory:'EntertainmentApplication',operatingSystem:'Any',isAccessibleForFree:true,description:routes[0][2],...(canonical?{url:canonical}:{}),offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}});
  else if(route)structured.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',...(origin?{item:origin+'/'}:{})},{'@type':'ListItem',position:2,name:route[1].split('|')[0].trim(),...(canonical?{item:canonical}:{})}]});
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="#fff9f6"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${indexable&&route?'index,follow':'noindex,nofollow'}">${canonical?`<link rel="canonical" href="${esc(canonical)}">`:''}<meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}">${canonical?`<meta property="og:url" content="${esc(canonical)}">`:''}<meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/manrope-400.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${JSON.stringify(structured).replace(/</g,'\\u003c')}</script><script type="module" src="/assets/client.js"></script></head><body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Chinese Gender Predictor home"><span class="brand-mark">${icon('moon')}</span><span>Chinese Gender<span class="brand-sub">Predictor</span></span></a><nav class="desktop-nav" aria-label="Main navigation">${[['/','Predictor'],['/how-it-works/','How it works'],['/chinese-gender-calendar-2027/','2027 calendar'],['/accuracy/','Is it accurate?']].map(([href,label])=>`<a href="${href}"${path===href?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-actions"><button class="icon-button menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav">${icon('list')}</button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden><a href="/">Predictor</a><a href="/how-it-works/">How it works</a><a href="/chinese-gender-calendar-2027/">2027 calendar</a><a href="/lunar-age-calculator/">Lunar age calculator</a><a href="/accuracy/">Is it accurate?</a></nav></header>
  <main id="main"><noscript><div class="container"><p class="no-js">Enable JavaScript to use the calculators. The chart and guides can still be read without it.</p></div></noscript>${body}</main>
  <footer class="site-footer"><div class="container footer-top"><a class="brand" href="/"><span class="brand-mark">${icon('moon')}</span><span>Chinese Gender<span class="brand-sub">Predictor</span></span></a><p>A traditional guessing game.<br>A little curiosity, just for fun.</p><nav aria-label="Footer"><a href="/lunar-age-calculator/">Lunar age calculator</a><a href="/about/">About & sources</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></nav></div><div class="container footer-bottom"><span>© 2026 Chinese Gender Predictor</span><span>For entertainment. Not a medical prediction.</span></div></footer></body></html>`;
}
export function form({ageOnly=false}={}) {
  return `<form id="${ageOnly?'age-form':'predictor-form'}" class="calculator-form" novalidate>
  <div class="form-heading"><span class="form-icon">${icon(ageOnly?'calendar':'sparkle')}</span><h2>${ageOnly?'Find your lunar age':'Let’s make a little guess'}</h2></div>
  ${ageOnly?'':`<fieldset class="mode-select"><legend>I know my</legend><div class="segmented"><label><input type="radio" name="date-mode" value="conception" checked><span>Conception date</span></label><label><input type="radio" name="date-mode" value="due"><span>Due date</span></label></div></fieldset>`}
  <div class="field-grid"><div class="field"><label for="birth-date">${ageOnly?'Your date of birth':'Mother’s date of birth'}</label><input id="birth-date" type="date" min="1900-01-01" max="2099-12-31" required aria-describedby="birth-hint"><p id="birth-hint" class="field-hint">Use the date on your birth certificate.</p></div><div class="field"><label for="target-date" id="target-label">${ageOnly?'Calculate age on':'Conception date'}</label><input id="target-date" type="date" min="1900-01-01" max="2099-12-31" required aria-describedby="target-hint"><p id="target-hint" class="field-hint">${ageOnly?'The date you want to check.':'Your best estimate is fine.'}</p></div></div>
  <p class="form-error" id="form-error" role="alert" hidden></p>
  ${ageOnly?'':`<div class="fun-note">${icon('info')}<p>This is a folk tradition, not a scientific prediction.<br><a href="/accuracy/">What does the research say?</a></p></div>`}
  <button class="button primary submit-button" type="submit" disabled>${ageOnly?'Calculate lunar age':'See my prediction'}${icon('sparkle')}</button>
  <div class="form-bottom"><span>${icon('shield-check')}Dates stay in your browser</span><button class="text-button" type="button" data-example>Try an example</button></div>
  </form>`;
}
export function resultPanel({ageOnly=false}={}) {
  return `<aside class="result-panel" id="result-panel" aria-label="${ageOnly?'Lunar age':'Prediction'} result"><div class="result-art"><img src="/assets/moon-mobile.jpg" width="1100" height="733" alt="Porcelain crescent moon, blush pink sphere, and gold star with a powder-blue bead hanging against a warm cream background." fetchpriority="high"></div><div class="result-content" id="result-content" aria-live="polite"><div class="empty-result"><span class="result-eyebrow">A MOMENT OF CURIOSITY</span><h2>${ageOnly?'Your age, by the lunar calendar.':'Boy or girl?<br>Let the tradition guess.'}</h2><p>${ageOnly?'Enter two dates to see your traditional Chinese age and how it is calculated.':'Enter your dates to explore the chart. We’ll show the lunar age and month behind your result.'}</p><div class="empty-details"><span>Lunar age <b>Not calculated</b></span><span>${ageOnly?'Lunar birth year':'Lunar month'} <b>Not calculated</b></span></div></div></div></aside>`;
}
export function chartTable() {
  return `<div class="chart-toolbar"><div class="chart-key"><span class="key-boy">B <span>Boy</span></span><span class="key-girl">G <span>Girl</span></span></div><button class="button secondary small" data-print>${icon('printer')}Print chart</button></div><p id="chart-help" class="small-copy">Read across from the mother’s lunar age to the lunar month of conception. Months 1 to 12 are lunar months, not January to December.</p><div class="chart-scroll" tabindex="0" role="region" aria-label="Traditional Chinese gender chart" aria-describedby="chart-help"><table class="gender-chart"><caption>Traditional Chinese gender chart: lunar ages 18 to 45</caption><thead><tr><th scope="col">Lunar age</th>${Array.from({length:12},(_,i)=>`<th scope="col" aria-label="Lunar month ${i+1}">${i+1}</th>`).join('')}</tr></thead><tbody>${Object.entries(CHART).map(([age,row])=>`<tr data-age="${age}"><th scope="row">${age}</th>${[...row].map((code,i)=>`<td data-month="${i+1}" class="${code==='B'?'boy':'girl'}"><span aria-label="${code==='B'?'Boy':'Girl'}">${code}</span></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="chart-footnote">For entertainment only. One commonly circulated version. Other charts may differ. <a href="/how-it-works/#chart-source">See our source and leap-month rule.</a></p>`;
}
export const faqs = [
  ['What is a Chinese gender predictor?','It is a traditional guessing game that matches the mother’s lunar age at conception with the lunar conception month on a chart. The result is for entertainment and does not determine a baby’s sex.'],
  ['Is the Chinese gender calendar accurate?','There is no good evidence that it works better than chance. A study of more than 2.8 million births found no meaningful predictive value. Our accuracy guide links to the original research.'],
  ['Should I enter my regular age or my lunar age?','Enter your regular date of birth. This calculator works out your lunar age for you using the Chinese calendar. It does not simply add one to your current age.'],
  ['What if I only know my due date?','Choose Due date above. We estimate conception as 266 days before that date. This is an approximation, and an uncertain conception date can cross a lunar-month boundary.'],
  ['Why do different calculators give different results?','Circulating chart versions can differ. Calculators may also use different age rules, date conversions or leap-month conventions. We show the inputs and explain the version we use.'],
  ['Are my dates saved or shared?','No. The calculations happen in your browser. We do not send your birth date or conception date to a server, put them in a link, or save them after you close the page.']
];
export function home() {
  return `<section class="container tool-section"><div class="intro"><div class="eyebrow">A little curiosity, while you wait.</div><h1>Chinese Gender Predictor</h1><p>Explore the traditional Chinese gender calendar with your dates. A little guess for your growing family.</p></div><div class="tool-grid">${form()}${resultPanel()}</div><div class="under-tool"><span>${icon('calendar')}Automatic lunar conversion</span><span>${icon('heart')}Always free to explore</span><span>${icon('shield-check')}No account needed</span></div></section>
  <section class="how-section" id="how-it-works"><div class="container how-layout"><div class="section-heading"><h2>A tradition made<br>easy to explore.</h2><p>Two dates become two lunar coordinates.<br>Here’s what happens behind your guess.</p><a class="text-link" href="/how-it-works/">See the full method ${icon('arrow-right')}</a></div><ol class="steps"><li><span class="step-icon">${icon('calendar')}</span><div><h3>Start with your dates</h3><p>Enter your birth date and an estimated conception date, or use your due date.</p></div></li><li><span class="step-icon">${icon('moon')}</span><div><h3>We find the lunar match</h3><p>Your dates are converted to your lunar age and the lunar month of conception.</p></div></li><li><span class="step-icon">${icon('sparkle')}</span><div><h3>Explore the chart’s guess</h3><p>See the traditional result, along with the exact chart coordinates used.</p></div></li></ol></div></section>
  <section class="container chart-section" id="chinese-gender-chart"><div class="section-heading"><div class="eyebrow">THE TRADITIONAL CHART</div><h2>The Chinese gender chart</h2><p>Prefer to look it up yourself? Find the intersection of lunar age and lunar month.</p></div>${chartTable()}</section>
  <section class="container guide-section"><div class="guide-banner"><div class="guide-mark">${icon('moon')}</div><div><h2>A new year. A different lunar calendar.</h2><p>The chart stays the same, but the dates change. Explore the 2027 lunar month reference.</p></div><a class="button secondary" href="/chinese-gender-calendar-2027/">2027 calendar ${icon('calendar')}</a></div><div class="honesty-note">${icon('info')}<div><h3>A little fun, with an honest answer.</h3><p>A well-converted date does not make a prediction scientific. Research has found this tradition no better than chance. <a href="/accuracy/">Read the evidence.</a></p></div></div></section>
  <section class="container faq-section" id="faq"><h2>A few things you might wonder.</h2><div class="faq-list">${faqs.map(([q,a])=>`<details><summary>${q}${icon('caret-down')}</summary><p>${a}${q.startsWith('Is the')?' <a href="/accuracy/">See the research.</a>':''}</p></details>`).join('')}</div></section>`;
}
