import {readFileSync} from 'node:fs';
import {CHART} from './chart.mjs';
export const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(name,extra='') {
  return readFileSync(`node_modules/@phosphor-icons/core/assets/regular/${name}.svg`,'utf8').replace('<svg ',`<svg class="icon ${extra}" aria-hidden="true" focusable="false" `);
}
const monthFrame=()=>`<span class="brand-month-frame" aria-hidden="true">${Array.from({length:12},()=>'<i></i>').join('')}</span>`;
export function previewPicture(slug,alt,{sizes='(max-width: 767px) calc(100vw - 86px), 430px'}={}) {
  return `<picture><source type="image/webp" srcset="/assets/games-${slug}-preview-320.webp 320w, /assets/games-${slug}-preview.webp 540w" sizes="${sizes}"><img src="/assets/games-${slug}-preview.png" alt="${esc(alt)}" width="540" height="764" loading="lazy" decoding="async"></picture>`;
}
export const routes = [
  ['/', 'Chinese Gender Predictor | Free Chinese Gender Calendar', 'Try a free Chinese gender predictor with automatic lunar age and month conversion. Explore the traditional chart and see how your result is calculated.'],
  ['/lunar-age-calculator/', 'Lunar Age Calculator | Chinese Age by Date', 'Calculate your traditional Chinese lunar age on any date. See the lunar birth year, target year and the formula behind your result.'],
  ['/chinese-gender-calendar-2027/', 'Chinese Gender Calendar 2027 | Chart & Free PDF', 'Use the 2027 Chinese gender chart with lunar month dates, age rules and free A4 or Letter PDFs. Includes due-date examples across 2026 and 2027.'],
  ['/chinese-gender-calendar-2026/', 'Chinese Gender Calendar 2026 | Chart & Free PDF', 'Explore the 2026 Chinese gender calendar, convert conception dates to lunar months, and download the complete chart and date reference as a free PDF.'],
  ['/gender-reveal-games/', '5 Free Printable Gender Reveal Games | PDF Kit', 'Download five gender reveal games: prediction cards, voting, a name race, eight Bingo cards and a word scramble. Free A4 and Letter PDFs with answers.'],
  ['/old-wives-tales-gender-prediction/', 'Old Wives’ Tales Gender Prediction | Guide & Free Game', 'Explore eight pregnancy folklore guesses, what research says, and a free printable old wives’ tales gender reveal game. Download A4 or Letter PDFs.'],
  ['/how-it-works/', 'How the Chinese Gender Predictor Works', 'Understand lunar age, conception month, leap months and the traditional chart used by this Chinese gender predictor. See a worked example.'],
  ['/accuracy/', 'Is the Chinese Gender Predictor Accurate? The Evidence', 'Is the Chinese gender predictor accurate? Read what studies found, why charts can give different answers, and how to learn your baby’s sex.'],
  ['/about/', 'About Chinese Gender Predictor', 'Learn about Chinese Gender Predictor, explore our free calendars and games, and see the sources behind the traditional chart.'],
  ['/privacy/', 'Privacy | Chinese Gender Predictor', 'How this website handles dates and calculations. Inputs stay in your browser and are not included in URLs or analytics.'],
  ['/terms/', 'Terms of Use | Chinese Gender Predictor', 'The Chinese gender predictor is a traditional entertainment tool. Read the scope, limitations and terms for using this website.']
];
export function shell(path,body,{origin='',indexable=false,title,description}={}) {
  const route=routes.find(r=>r[0]===path);
  title ||= route?.[1]||'Page not found | Chinese Gender Predictor'; description ||=route?.[2]||'Find the Chinese gender predictor and our guides.';
  const canonical=origin?new URL(path,origin).href:'';
  const structured = [{ '@context':'https://schema.org','@type':'WebSite',name:'Chinese Gender Predictor',...(origin?{url:origin+'/'}:{}),inLanguage:'en'}];
  if(path==='/')structured.push({'@context':'https://schema.org','@type':'WebApplication',name:'Chinese Gender Predictor',applicationCategory:'EntertainmentApplication',operatingSystem:'Any',isAccessibleForFree:true,description:routes[0][2],...(canonical?{url:canonical}:{}),offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}});
  else if(route)structured.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',...(origin?{item:origin+'/'}:{})},{'@type':'ListItem',position:2,name:route[1].split('|')[0].trim(),...(canonical?{item:canonical}:{})}]});
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="#fff9f6"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${indexable&&route?'index,follow':'noindex,nofollow'}">${canonical?`<link rel="canonical" href="${esc(canonical)}">`:''}<meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}">${canonical?`<meta property="og:url" content="${esc(canonical)}">`:''}${origin?`<meta property="og:image" content="${esc(origin)}/assets/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Chinese Gender Predictor: a little guess for your growing family"><meta name="twitter:image" content="${esc(origin)}/assets/social-preview.png">`:""}<meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/manrope-400.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/cormorant-600-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${JSON.stringify(structured).replace(/</g,'\\u003c')}</script><script type="module" src="/assets/client.js"></script></head><body class="${path==='/'?'page-home':'page-guide'}">
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Chinese Gender Predictor home"><span class="brand-mark">${monthFrame()}${icon('moon')}</span><span>Chinese Gender<span class="brand-sub">Predictor</span></span></a><nav class="desktop-nav" aria-label="Main navigation">${[['/','Predictor'],['/lunar-age-calculator/','Lunar age'],['/chinese-gender-calendar-2027/','2027 calendar'],['/gender-reveal-games/','Printable games'],['/accuracy/','Is it accurate?']].map(([href,label])=>`<a href="${href}"${path===href?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-actions"><button class="icon-button menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav">${icon('list')}</button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden><a href="/"${path==='/'?' aria-current="page"':''}>Predictor</a><a href="/how-it-works/"${path==='/how-it-works/'?' aria-current="page"':''}>How it works</a><a href="/chinese-gender-calendar-2027/"${path==='/chinese-gender-calendar-2027/'?' aria-current="page"':''}>2027 calendar</a><a href="/chinese-gender-calendar-2026/"${path==='/chinese-gender-calendar-2026/'?' aria-current="page"':''}>2026 calendar</a><a href="/gender-reveal-games/"${path==='/gender-reveal-games/'?' aria-current="page"':''}>Printable games</a><a href="/old-wives-tales-gender-prediction/"${path==='/old-wives-tales-gender-prediction/'?' aria-current="page"':''}>Old wives’ tales</a><a href="/lunar-age-calculator/"${path==='/lunar-age-calculator/'?' aria-current="page"':''}>Lunar age calculator</a><a href="/accuracy/"${path==='/accuracy/'?' aria-current="page"':''}>Is it accurate?</a></nav></header>
  <main id="main"><noscript><div class="container"><p class="no-js">Enable JavaScript to use the calculators. The chart and guides can still be read without it.</p></div></noscript>${body}</main>
  <footer class="site-footer"><div class="container footer-top"><a class="brand" href="/"><span class="brand-mark">${monthFrame()}${icon('moon')}</span><span>Chinese Gender<span class="brand-sub">Predictor</span></span></a><p>A traditional guessing game.<br>A little curiosity, just for fun.</p><nav aria-label="Footer"><a href="/chinese-gender-calendar-2026/">2026 calendar</a><a href="/chinese-gender-calendar-2027/">2027 calendar</a><a href="/gender-reveal-games/">Printable games</a><a href="/old-wives-tales-gender-prediction/">Old wives’ tales</a><a href="/how-it-works/">How it works</a><a href="/lunar-age-calculator/">Lunar age calculator</a><a href="/about/">About & sources</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></nav></div><div class="container footer-bottom"><span>© 2026 Chinese Gender Predictor</span><span>For entertainment. Not a medical prediction.</span></div></footer></body></html>`;
}
function dateField(id,label,hint) {
  const prefix=id.split('-')[0];
  const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `<fieldset class="field date-field" id="${id}" data-date-field><legend class="field-label" id="${prefix}-label">${label}</legend><div class="date-parts"><label class="sr-only" id="${prefix}-month-label" for="${id}-month">Month</label><span class="date-select"><select id="${id}-month" data-date-part="month" aria-labelledby="${prefix}-label ${prefix}-month-label" aria-describedby="${prefix}-hint" required><option value="">Month</option>${months.map((name,i)=>`<option value="${i+1}">${name}</option>`).join('')}</select>${icon('caret-down')}</span><label class="sr-only" id="${prefix}-day-label" for="${id}-day">Day</label><span class="date-select"><select id="${id}-day" data-date-part="day" aria-labelledby="${prefix}-label ${prefix}-day-label" aria-describedby="${prefix}-hint" required><option value="">Day</option>${Array.from({length:31},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')}</select>${icon('caret-down')}</span><label class="sr-only" id="${prefix}-year-label" for="${id}-year">Year</label><input id="${id}-year" data-date-part="year" type="text" inputmode="numeric" maxlength="4" placeholder="Year" aria-labelledby="${prefix}-label ${prefix}-year-label" aria-describedby="${prefix}-hint" autocomplete="off" required></div><p id="${prefix}-hint" class="field-hint">${hint}</p></fieldset>`;
}
export function form({ageOnly=false}={}) {
  return `<form id="${ageOnly?'age-form':'predictor-form'}" class="calculator-form" novalidate>
  <div class="form-heading"><span class="form-icon">${icon(ageOnly?'calendar':'sparkle')}</span><h2>${ageOnly?'Find your lunar age':'Let’s make a little guess'}</h2></div>
  ${ageOnly?'':`<fieldset class="mode-select"><legend>I know my</legend><div class="segmented"><label><input type="radio" name="date-mode" value="conception" checked><span>Conception date</span></label><label><input type="radio" name="date-mode" value="due"><span>Due date</span></label></div></fieldset>`}
  <div class="field-grid">${dateField('birth-date',ageOnly?'Your date of birth':'Mother’s date of birth','Use your regular birthday.')}${dateField('target-date',ageOnly?'Calculate age on':'Conception date',ageOnly?'Choose today for your current age.':'Your best estimate is fine.')}</div>
  <p class="form-error" id="form-error" role="alert" hidden></p>
  ${ageOnly?'':`<div class="fun-note">${icon('info')}<p>Folklore for lunar ages 18 to 45. Not a scientific prediction.<br> <a href="/accuracy/">What does the research say?</a></p></div>`}
  <button class="button primary submit-button" type="submit" disabled>${ageOnly?'Calculate lunar age':'See my prediction'}${icon('sparkle')}</button>
  <div class="form-bottom"><span>${icon('shield-check')}Your dates stay private</span><button class="text-button" type="button" data-example>Try an example</button></div>
  </form>`;
}
export function resultPanel({ageOnly=false}={}) {
  const art=ageOnly?'<div class="result-art"><picture><source type="image/webp" srcset="/assets/moon-mobile-660.webp"><img src="/assets/moon-mobile.jpg" width="1100" height="733" alt="" fetchpriority="high"></picture></div>':`<div class="result-art art-instrument" aria-hidden="true"><div class="lunar-instrument" id="lunar-instrument"><div class="lunar-dial"><ol class="lunar-month-ring">${Array.from({length:12},(_,i)=>`<li data-lunar-month="${i+1}">${i+1}</li>`).join('')}</ol><div class="lunar-dial-center"><picture><source type="image/webp" srcset="/assets/moon-dial-420.webp"><img src="/assets/moon-mobile.jpg" width="420" height="420" alt="" fetchpriority="high"></picture></div></div><p class="instrument-caption">Your lunar age and month appear here.</p></div></div>`;
  return `<aside class="result-panel" id="result-panel" aria-label="${ageOnly?'Lunar age':'Prediction'} result">${art}<div class="result-content" id="result-content"><div class="empty-result"><span class="result-eyebrow">A little moment of wonder</span><h2>${ageOnly?'Your age, by the lunar calendar.':'Boy or girl?<br>Let the tradition guess.'}</h2><p>${ageOnly?'Enter two dates to see your traditional Chinese age and how it is calculated.':'Enter your dates to explore the chart. We’ll show the lunar age and month behind your result.'}</p><div class="empty-details"><span>Lunar age <b>Not calculated</b></span><span>${ageOnly?'Lunar birth year':'Lunar month'} <b>Not calculated</b></span></div></div></div></aside>`;
}
export function chartTable() {
  return `<div class="chart-toolbar"><div class="chart-key"><span class="key-boy">B <span>Boy</span></span><span class="key-girl">G <span>Girl</span></span></div><button class="button secondary small" data-print>${icon('printer')}Print chart</button></div><p id="chart-help" class="small-copy">Read across from the mother’s lunar age to the lunar month of conception. Months 1 to 12 are lunar months, not January to December.</p><div class="chart-scroll" tabindex="0" role="region" aria-label="Traditional Chinese gender chart" aria-describedby="chart-help"><table class="gender-chart"><caption>Traditional Chinese gender chart: lunar ages 18 to 45</caption><thead><tr><th scope="col">Lunar age</th>${Array.from({length:12},(_,i)=>`<th scope="col" aria-label="Lunar month ${i+1}">${i+1}</th>`).join('')}</tr></thead><tbody>${Object.entries(CHART).map(([age,row])=>`<tr data-age="${age}"><th scope="row">${age}</th>${[...row].map((code,i)=>`<td data-month="${i+1}" class="${code==='B'?'boy':'girl'}"><span aria-label="${code==='B'?'Boy':'Girl'}">${code}</span></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="chart-footnote">For entertainment only. Traditional charts may give different answers. <a href="/how-it-works/#chart-source">See our source and leap-month rule.</a></p>`;
}
export const faqs = [
  ['What is a Chinese gender predictor?','It is a traditional chart that matches the mother’s lunar age at conception with the lunar month of conception. It gives a playful boy-or-girl guess, not a medical prediction.'],
  ['How do I use the Chinese gender calendar?','Enter the mother’s date of birth and an estimated conception date. We find the lunar age and month for you. To read the chart yourself, find the age row and month column; the cell where they meet contains the chart’s guess.',['/how-it-works/#start-with-regular-calendar-dates','Follow the steps for using the chart.']],
  ['How accurate is the Chinese gender calendar?','Studies have found that the calendar is no more reliable than chance. Correctly converting your dates helps you read the chart, but it does not make the guess a reliable prediction.',['/accuracy/#calendar-accuracy','Read the accuracy studies.']],
  ['How do I find my lunar age for the chart?','Enter your regular date of birth and your estimated conception date above. Traditional lunar age starts at one at birth and increases at each Chinese New Year. It is not always your regular age plus one.',['/lunar-age-calculator/#my-lunar-age','Calculate your lunar age separately.']],
  ['How do I find my lunar month of conception?','It is the Chinese-calendar month containing your estimated conception date. Lunar months do not line up with January through December. Enter your usual calendar date above, and the calculator finds the lunar month for you.',['/how-it-works/#lunar-month-of-conception','See examples of lunar conception months.']],
  ['What if I only know my due date?','Choose Due date above. We estimate conception as 266 days before that date. The chart uses this estimated conception date, not the month your baby is due. A small difference in the estimate can sometimes change the lunar month used.',['/how-it-works/#conception-date-or-due-date','Learn which date to use.']],
  ['Does the Chinese gender calendar change every year?','The chart used here stays the same. The dates of the lunar months change from year to year, and your lunar age can change too. Our yearly calendars help you find the lunar month for a specific conception date.',['/chinese-gender-calendar-2027/#year-changes','Explore the yearly calendar dates.']],
  ['Why do different calculators give different results?','Websites may use different chart versions, ways of counting age, conception estimates or leap-month rules. Your result shows the lunar age and month used here, so you can find the matching cell on our chart.',['/how-it-works/#chart-source','See the chart and rules used here.']],
  ['Are my dates saved or shared?','No. Your dates and result stay on your device. We do not receive or save them. If you copy your result, the shared text includes no dates.']
];
export function home() {
  return `<section class="container tool-section" id="predictor"><div class="intro"><h1>Chinese Gender <span>Predictor</span></h1><p>Explore the Chinese gender calendar with your dates. A little guess for your growing family.</p></div><div class="tool-grid">${form()}${resultPanel()}</div></section>
  <section class="how-section" id="how-it-works"><div class="container how-layout"><div class="section-heading"><h2>A tradition made<br>easy to explore.</h2><p>Enter your dates and find your place on the traditional Chinese gender chart.</p><a class="text-link" href="/how-it-works/">How to use the chart ${icon('arrow-right')}</a></div><ol class="steps"><li><span class="step-icon">${icon('calendar')}</span><div><h3>Start with your dates</h3><p>Enter your birth date and an estimated conception date, or use your due date.</p></div></li><li><span class="step-icon">${icon('moon')}</span><div><h3>We find your lunar age and month</h3><p>Your dates are converted to your lunar age and the lunar month of conception.</p></div></li><li><span class="step-icon">${icon('sparkle')}</span><div><h3>Explore the chart’s guess</h3><p>See the chart’s guess and the lunar age and month used for it.</p></div></li></ol></div></section>
  <section class="container chart-section" id="chinese-gender-chart"><div class="section-heading"><div class="eyebrow">THE TRADITIONAL CHART</div><h2>The Chinese gender chart</h2><p>Also called a Chinese birth chart or Chinese pregnancy calendar, this traditional chart uses lunar age and lunar month. It does not use your birthday zodiac sign.</p></div>${chartTable()}</section>
  <section class="container guide-section"><div class="resource-heading"><h2>A little more to explore.</h2><p>Keep the calendar close, or bring a little play to your gathering.</p></div><div class="resource-shelf"><a class="calendar-feature" href="/chinese-gender-calendar-2027/"><span class="resource-type">The lunar calendar</span><strong class="calendar-year">2027</strong><h3>A new year, in lunar months.</h3><p>Dates, the full chart, and a printable calendar to keep.</p><span class="resource-action">Explore the 2027 calendar ${icon('arrow-up-right')}</span></a><a class="games-feature" href="/gender-reveal-games/"><div class="resource-preview">${previewPicture('prediction-cards','Printable prediction cards with space for a guess and a wish.',{sizes:'(max-width: 767px) 136px, 158px'})}${previewPicture('bingo','A preview of the printable party Bingo cards.',{sizes:'(max-width: 767px) 136px, 158px'})}</div><div><span class="resource-type">For your gathering</span><h3>Small games. Lovely memories.</h3><p>Five free activities, ready to print.</p><span class="resource-action">Browse the printable games ${icon('arrow-up-right')}</span></div></a></div><nav class="supporting-guides" aria-label="More calendar guides"><a href="/lunar-age-calculator/">Find your lunar age ${icon('arrow-up-right')}</a><a href="/chinese-gender-calendar-2026/">Looking for 2026? ${icon('arrow-up-right')}</a><a href="/old-wives-tales-gender-prediction/">Explore other folklore ${icon('arrow-up-right')}</a></nav><div class="honesty-note">${icon('info')}<div><h3>A little fun, with an honest answer.</h3><p>The calendar’s guess is just for fun. Research has found it no better than chance. <a href="/accuracy/#calendar-accuracy">Read the evidence.</a></p></div></div></section>
  <section class="container faq-section" id="faq"><h2>Questions about the calendar.</h2><div class="faq-list">${faqs.map(([q,a,link])=>`<details><summary>${esc(q)}${icon('caret-down')}</summary><p>${esc(a)}${link?` <a href="${esc(link[0])}">${esc(link[1])}</a>`:''}</p></details>`).join('')}</div></section>`;
}
